services:
  - type: web
    name: agriexpert
    env: python
    pythonVersion: "3.10.14"  #  FORCE Python 3.10
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn AgriExpertProject.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "True"  
      - key: ALLOWED_HOSTS
        value: "agriexpert.onrender.com,localhost,127.0.0.1"
      - key: DISABLE_COLLECTSTATIC
        value: "0"
